### ISSUE TITLE
tiebreak index does not exist

### ISSUE THREAD

**Issue by valpackett** [skim-rs/skim#536]
The readme says

> There are five sort keys for results: score, index, begin, end, length, you can specify how the records are sorted by sk --tiebreak score,index,-begin or any other order you want.

However…

https://github.com/lotabout/skim/blob/291fc34c58b1670a5e8c95f1e8f930b82c030b19/src/item.rs#L200-L209

`index` does not seem to exist at all??

**Comment by lotabout** [comment]
@valpackett It's a doc error. `index` was removed in commit 94846e7. Can't remember exactly why, but possibly sorting by `index` could be achieved by `--tac`.

**Comment by blueforesticarus** [comment]
Based on the documentation, it seems you are meant to be able to set the priority of tiebreakers by specifying multiple.  
From what I can tell, with `--tac` you cannot sort at all. 

This is rather unfortunate, as what I'd really like to do is sort by score, and then by index, so that *newest - perfect matches* show up first (in this case I am skimming browser history.)

**Comment by j-lakeman** [comment]
Then `--tiebreak=index` should probably be changed / removed from all shell binding files right? Like this one:
https://github.com/skim-rs/skim/blob/32d9e70af4eeaaf2c3f2d276838dc338361a75cf/shell/key-bindings.bash#L53

This would be an ez PR I could provide.

**Comment by LoricAndre** [comment]
I'd say removing it might not be the best option, but I'd love a PR that readds the index, as long as it includes the necessary tests to ensure that if there was a reason for it to be removed, we find it before it hits the repos.

**Comment by LoricAndre** [comment]
Note: I think I'll actually try my hand at this one, please tell me if you want to work on it to avoid duplicate PRs !

**Comment by j-lakeman** [comment]
Go for it!
